Container-aware Ergonomics
microsoft/openjdk-proposals pull request #12
Opened 2023-04-11 23:32 UTC by brunoborges

Reviewers, please check our [Contributing Guide](../CONTRIBUTING.md) has been followed 
before accepting this PR.

2023-04-26 05:00 UTC, karianna requested changes
I've made a few suggested changes, but overall I think this could be improved by writing in an active voice.  Recommend a GPT pass to make it so :-)

2023-04-27 22:53 UTC, brunoborges commented on ergonomics_profiles/readme.md
> +Introduce ergonomics profiles and add a `balanced` option, for the existing heuristics, and a `dedicated` option for when the JVM is running on systems with dedicated resources for the one JVM proces
I'll keep this `balanced` for now, but will review back later.

2023-05-01 17:25 UTC, brunoborges commented on ergonomics_profiles/readme.md
> +1. Automatically select `dedicated` when the JVM believes the system is dedicated to it.
Done: [7fd7e8c](https://github.com/microsoft/openjdk-proposals/pull/12/commits/7fd7e8cc1de80e4557b88af99c327633f72b64c6)

2023-05-01 17:25 UTC, brunoborges commented on ergonomics_profiles/readme.md
> +Introduce ergonomics profiles and add a `balanced` option, for the existing heuristics, and a `dedicated` option for when the JVM is running on systems with dedicated resources for the one JVM proces
Alright, I changed to `shared` in [7fd7e8c](https://github.com/microsoft/openjdk-proposals/pull/12/commits/7fd7e8cc1de80e4557b88af99c327633f72b64c6)

2023-05-03 22:10 UTC, karianna reviewed
Lots of suggested edits for ease of reading.

2023-05-03 22:10 UTC, karianna commented on ergonomics_profiles/readme.md
> +The `dedicated` profile will contain different heuristics aimed at maximizing resource consumption in the environment with the assumption that the environment is dedicated to the JVM.
```suggestion
The `dedicated` profile will contain different heuristics aimed at maximizing resource consumption in the environment, assuming that the environment is dedicated to the JVM.
```

2023-05-03 22:10 UTC, karianna commented on ergonomics_profiles/readme.md
> +This profile will maximize heap size allocation, optimize garbage collector selection with a larger set of options and considerations, vary the active processor counting, set different values for gar
```suggestion
This profile will maximize heap size allocation, optimize garbage collector selection with a more extensive set of options and considerations, vary the active processor counting, set different values for garbage collector threads, more aggressively size native memory expectation, and size internal JVM thread pools accordingly.
```

2023-05-03 22:10 UTC, karianna commented on ergonomics_profiles/readme.md
> +To allow the backporting of this feature to older versions of OpenJDK, the value may also be obtained through the `MBeanServerConnection.getAttribute` method:
```suggestion
The value may also be obtained through the `MBeanServerConnection.getAttribute` method to allow the backporting of this feature to older versions of OpenJDK:
```

2023-05-03 22:10 UTC, karianna commented on ergonomics_profiles/readme.md
> +At this moment, the only alternative to this proposal is by manualling tuning the JVM. This exercise is very often complex, difficult, and time consuming for Java developers.
```suggestion
Currently, the only alternative to this proposal is manually tuning the JVM. This exercise is often complex, challenging, and time-consuming for Java developers.
```

2023-05-03 22:10 UTC, karianna commented on ergonomics_profiles/readme.md
> +// to validate this enhancement, beyond the usual mandatory unit tests?
```suggestion
// to validate this enhancement beyond the usual mandatory unit tests?
```

2023-05-03 22:10 UTC, karianna commented on ergonomics_profiles/readme.md
> +1. [JDK-8261242: [Linux] OSContainer::is_containerized() returns true when run outside a container](https://bugs.openjdk.org/browse/JDK-8261242)
```suggestion
1. [JDK-8261242: \[Linux\] OSContainer::is_containerized() returns true when run outside a container](https://bugs.openjdk.org/browse/JDK-8261242)
```

2023-05-03 22:10 UTC, karianna commented on ergonomics_profiles/readme.md
> +List of related issues, in no particular order, that may have to be addressed before this JEP, or that this JEP may have address as part of its implementation:
```suggestion
List of related issues, in no particular order, that may have to be addressed before this JEP or that this JEP may have to address as part of its implementation:
```

2023-05-03 22:10 UTC, karianna commented on ergonomics_profiles/readme.md
> +The default JVM ergonomics were designed to be balanced with shared resources, with the understanding that it would share resources with other processes (e.g., a data store) running on a shared envir
```suggestion
The default JVM ergonomics were designed to share resources with other processes (e.g., a data store) running on a shared environment, such as a bare metal server or a large virtual machine.
```

2023-05-03 22:10 UTC, karianna commented on ergonomics_profiles/readme.md
> +On a study done by an APM vendor (New Relic), it was identified that more than 60% of monitored JVMs in production are running inside environments with resources dedicated to the JVM (i.e., In contai
```suggestion
On a study done by an APM vendor (New Relic), it was identified that more than 60% of monitored JVMs in production are running inside environments with resources dedicated to the JVM (i.e., In containers), as opposed to being shared. A large percentage of those JVMs with dedicated resources were running without explicit JVM tuning flags. Therefore the JVM was running with default ergonomics traditionally aimed at shared environments.
```

2023-05-03 22:10 UTC, karianna commented on ergonomics_profiles/readme.md
> +Further on, it is likely that the JVM does not need to reclaim heap memory as soon as it does in shared environments, as the JVM is the only process running on the system. This means that the JVM may
```suggestion
Further on, it is likely that the JVM can reclaim heap memory later than it does in shared environments, as the JVM is the only process running on the system. This means that the JVM may set the initial heap size as maximum heap size, while having a suitable minimum heap size for other memory pools consumption (e.g. native memory). This shall signal to the garbage collector to delay, or act more lazily, on the action of cleaning and reclaiming heap.
```

2023-05-03 22:28 UTC, brunoborges commented on ergonomics_profiles/readme.md
> +1. Introduce a `dedicated` profile designed for systems where the JVM is effectively the only process using resources, e.g. In a canonical container deployment scenario.
Perhaps a better way to day is "is the primary process"

2023-05-04 03:55 UTC, karianna approved these changes

2023-05-04 04:37 UTC, merged

2023-05-23 18:51 UTC, DanHeidinga reviewed
Some late comments after reading the draft

2023-05-23 18:51 UTC, DanHeidinga commented on ergonomics_profiles/readme.md
> +Users may also select a profile by setting this flag in the environment variable `JAVA_TOOL_OPTIONS`.
Is there a reason to call out this env var and not others like `JDK_JAVA_OPTIONS`?